EUREKA_ZONE_HOST: 172.18.146.173
EUREKA_ZONE_PORT: 7000
CONFIG_HOST: 172.18.146.173
CONFIG_PORT: 7009
CONSOLE_LOG_PATH: /apps/logs
DATASOURCE_HOST: 172.18.146.198
DATASOURCE_PORT: 8808
DATASOURCE_USERNAME: admin
DATASOURCE_PASSWORD: Wanbit.2013
DATASOURCE_NAME: dy-pro
DATASOURCE_DRUID_MAXACTIVE: 20
DATASOURCE_DRUID_INITIALSIZE: 20
DATASOURCE_DRUID_MINIDLE: 20
DATASOURCE_DRUID_MAXWAIT: 60000
REDIS_NODES: r-wz9c465399031344.redis.rds.aliyuncs.com
REDIS_NODES_PORT: 6379
REDIS_NODES_PWD: Wanbit.2013
RABBITMQ_USERNAME: admin
RABBITMQ_PASSWORD: Wanbit.2013
RABBITMQ_HOST: 172.18.146.208
RABBITMQ_PORT: 5672
RABBITMQ_VHOST: dy

spring:
  redis:
    host: ${REDIS_NODES:192.168.1.233}
    port: ${REDIS_NODES_PORT:6379}
    pool:
      max-idle: 20
      min-idle: 20
      max-active: 20
      max-wait: -1

witc:
  dev-model: true
  dingTalk:
    url: https://oapi.dingtalk.com/robot/send?access_token=837418a67ac4ca2a3df4ef34189ee13f1766aa006f8b6545a910120cdea054bd
    package-prefix: com.witc

# AES密码加密私钥(Base64加密)
encryptAESKey: V2FuZzkyNjQ1NGRTQkFQSUpXVA==
# JWT认证加密私钥(Base64加密)
encryptJWTKey: U0JBUElKV1RkV2FuZzkyNjQ1NA==
# AccessToken过期时间-5分钟-5*60(秒为单位)
accessTokenExpireTime: -1
# RefreshToken过期时间-30分钟-30*60(秒为单位)
refreshTokenExpireTime: 1800
# Shiro缓存过期时间-5分钟-5*60(秒为单位)(一般设置与AccessToken过期时间一致)
shiroCacheExpireTime: 300

logging:
  level:
    root: INFO
    com.witc: INFO

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 11000
          strategy: SEMAPHORE
#ribbon的超时时间
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
